import { ScaleConstructor } from './GenericalScale';
import {
  PentatonicScale,
  MajorPentatonicScale,
  ChromaticScale,
  MajorScale,
  MinorNaturalScale,
  MinorHarmonicScale,
  MinorMelodicScale,
  AlgerianScale,
  AlteredScale,
  AugmentedScale,
  BebopDominantScale,
  BluesScale,
  DorianScale,
  DoubleHarmonicScale,
  EnigmaticScale,
  FlamencoScale,
  GypsyScale,
  HalfDiminishedScale,
  HarmonicMajorScale,
  HungarianMinorScale,
  HungarianMajorScale,
  InScale,
  InSenScale,
  IstrianScale,
  IwatoScale,
  LocrianScale,
  LocrianMajorScale,
  LydianScale,
  LydianAugmentedScale,
  BebopMajorScale,
  MixolydianScale,
  PersianScale,
  PhrygianDominantScale,
  PhrygianScale,
  TritoneScale,
  UkrainianDorianScale,
} from './Scales';

// Registre des gammes
export const scalesRegistry: Record<string, ScaleConstructor> = {
  pentatonic: PentatonicScale,
  majorPentatonic: MajorPentatonicScale,
  chromatic: ChromaticScale,
  major: MajorScale,
  minorNatural: MinorNaturalScale,
  minorHarmonic: MinorHarmonicScale,
  minorMelodic: MinorMelodicScale,
  algerian: AlgerianScale,
  altered: AlteredScale,
  augmented: AugmentedScale,
  bebopDominant: BebopDominantScale,
  blues: BluesScale,
  dorian: DorianScale,
  doubleHarmonic: DoubleHarmonicScale,
  enigmatic: EnigmaticScale,
  flamenco: FlamencoScale,
  gypsy: GypsyScale,
  halfDiminished: HalfDiminishedScale,
  harmonicMajor: HarmonicMajorScale,
  hungarianMinor: HungarianMinorScale,
  hungarianMajor: HungarianMajorScale,
  in: InScale,
  inSen: InSenScale,
  istrian: IstrianScale,
  iwato: IwatoScale,
  locrian: LocrianScale,
  locrianMajor: LocrianMajorScale,
  lydian: LydianScale,
  lydianAugmented: LydianAugmentedScale,
  bebopMajor: BebopMajorScale,
  mixolydian: MixolydianScale,
  persian: PersianScale,
  phrygianDominant: PhrygianDominantScale,
  phrygian: PhrygianScale,
  tritone: TritoneScale,
  ukrainianDorian: UkrainianDorianScale,
} as const;
